import React from 'react';
import { Document, Page, Text, Image, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        padding: 20,
    },
    header: {
        fontSize: 24,
        textAlign: 'center',
        marginBottom: 20,
    },
    subheader: {
        fontSize: 18,
        marginBottom: 10,
    },
    text: {
        fontSize: 12,
        marginBottom: 10,
        lineHeight: 1.5,
    },
    image: {
        width: '100%',
        height: 'auto',
        marginBottom: 20,
    },
    footer: {
        position: 'absolute',
        fontSize: 10,
        bottom: 30,
        left: 20,
        right: 20,
        textAlign: 'center',
    },
});

const PDFGenerator = ({ content, images }) => {
    const sections = content.split('\n').filter((line) => line.trim().length > 0);

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <Text style={styles.header}>Multi-Modal PDF Report</Text>
                {sections.map((section, index) => (
                    <React.Fragment key={index}>
                        <Text style={styles.text}>{section}</Text>
                        {images[index] && <Image style={styles.image} src={images[index]} />}
                    </React.Fragment>
                ))}
                <Text style={styles.footer}>Generated by Multi-Modal PDF Generator</Text>
            </Page>
        </Document>
    );
};

export default PDFGenerator;
